### ISSUE TITLE
Does adding options to medium by default overwrite default values?

### ISSUE THREAD

**Issue by patrickml** [firrae/react-mediumeditor#5]
We should look into this.

``` jsx
{
      toolbar: this.props.toolbar,
      anchor: this.props.anchor,
      anchorPreview: this.props.anchorPreview,
      placeholder: this.props.placeholder,
      anchorForm: this.props.anchorForm,
      paste: this.props.paste,
      keyboardCommands: this.props.keyboardCommands
}
```

**Comment by firrae** [comment]
From my understanding it modifies the ones specified and leaves the rest, but I'll look into what it's doing.

**Comment by firrae** [comment]
https://github.com/yabwe/medium-editor/blob/master/dist/js/medium-editor.js#L6230

This shows that it appends or replaces the default leaving the others intact.
